### ISSUE TITLE
IDISP016 is incorrectly triggered

### ISSUE THREAD

**Issue by jeremyVignelles** [DotNetAnalyzers/IDisposableAnalyzers#111]
I have a code like this:

```
                var cert = new X509Certificate2(certificateFilePath, CertificatePassword, X509KeyStorageFlags.Exportable);

                if (!CertificateIsValid(cert))
                {
                    cert.Dispose();
                    throw new InvalidOperationException("Invalid certificate");
                }
                this._certificates[certificateKind] = cert;
```

which triggers IDISP016 on `.Dispose()`. It should not, since I'm throwing and getting out of the function.

Besides, I have other places where I do something like:

```
cert.Dispose();
cert = new X509Certificate2(certificateFilePath, CertificatePassword, X509KeyStorageFlags.Exportable);

cert.DoSomething();
```

which triggers the analyzer too. What's wrong?

I've also seen these line in this repo, which seems wrong to me: You shouldn't have to hide warnings this way, because it is the same variable, but not the same value.

https://github.com/DotNetAnalyzers/IDisposableAnalyzers/blob/1a8b89d16fc4ccf1505d125baa3c23b652244d98/ValidCode/Recursion/Out.cs#L45-L54

**Comment by JohanLarsson** [comment]
Thanks for reporting, looks like I dumbed analysis there.

**Comment by JohanLarsson** [comment]
Think all are fixed now. For me it is easiest with many small issues. Nothing is too small.
