### ISSUE TITLE
IDISP003 When disposing an item inside a list

### ISSUE THREAD

**Issue by jeremyVignelles** [DotNetAnalyzers/IDisposableAnalyzers#112]
Example test:

```
        [Test]
        public void DisposingListContent()
        {
            var testCode = @"
namespace RoslynSandbox
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public class Foo
    {
        private List<Stream> _streams = new List<Stream>();

        public void Meh()
        {
            this._streams[0].Dispose();
            this._streams[0] = File.OpenRead(string.Empty);
        }
    }
}";

            AnalyzerAssert.Valid(Analyzer, testCode);
        }
```

granted, it's not a really nice piece of code because it is sensitive to race condition unless locked, but I'm disposing the item correctly.

**Comment by jeremyVignelles** [comment]
The code fix is not really useful either : `(this._streams as IDisposable)?.Dispose();`

**Comment by JohanLarsson** [comment]
Thanks for reporting! I need to try to fix some of the most embarrassing bugs this weekend.
Keep the issues coming!

**Comment by JohanLarsson** [comment]
We have a discord room if you feel like chatting: https://gitter.im/DotNetAnalyzers/IDisposableAnalyzers

**Comment by JohanLarsson** [comment]
~fixed~ it by excluding element access from analysis for now.
