### ISSUE TITLE
Should IDISP004 warn for explicit discard?

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/IDisposableAnalyzers#117]
```cs
_ = File.OpenRead(...);
```

**Comment by ErikWahlstrom** [comment]
Yes. It's more likely to be a bug than a desired discard.

**Comment by nulltoken** [comment]
@ErikWahlstrom Hrmpf... I wonder if that should really be considered as a bug in the general case. 

For instance #91 shows an example where that's not a bug but an explicit workaround to tell the analyzer "I know what I'm doing here".

Thoughts?

**Comment by JohanLarsson** [comment]
@nulltoken we can have both, the analyzer already keeps track of if it is sure or assumes that the instance is created.

For example for:
```cs
_ = File.OpenRead(...);
```

The analyzer knows that `File.OpenRead` returns a created disposable that should be disposed and discarding it is a bug. If we write 1 000 issues & fixes we can hopefully get to a spot where the analyzer is more useful than annoying.

**Comment by nulltoken** [comment]
@JohanLarsson 

>If we write 1 000 issues & fixes we can hopefully get to a spot where the analyzer is more useful than annoying.

Fits me. One step at a time, then 😉
