### ISSUE TITLE
Require GC.SuppressFinalize(this) when virtual dispose?

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/IDisposableAnalyzers#142]
```cs
public abstract class C : IDisposable
{
    public void Dispose()
    {
        this.Dispose(true);
        // Require GC.SuppressFinalize(this); here?
    }

    protected virtual void Dispose(bool disposing)
    {
        ...
    }
}
```

**Comment by JohanLarsson** [comment]
Guess we can have the rule, opt-out via .ruleset is easy enough.

**Comment by jeremyVignelles** [comment]
Require only if a finalizer is declared?

**Comment by JohanLarsson** [comment]
We have [IDISP018](https://github.com/DotNetAnalyzers/IDisposableAnalyzers/blob/master/documentation/IDISP018.md) that checks the finalizer case. Thinking we can have this as a separate rule to enable configuration via ruleset.

**Comment by jeremyVignelles** [comment]
what would be the difference then? Why should we have another rule?

**Comment by jeremyVignelles** [comment]
I still don't understand the difference.
As I understand it, IDISP018  means that you must call SuppressFinalize in the Dispose() method if the type has a finalizer.

What's the difference with this one then?

**Comment by JohanLarsson** [comment]
This one is the same thing but it nags if there is a virtual dispose method. Virtual meaning subclasses may add finalizers.

**Comment by sharwell** [comment]
In the current `Dispose` pattern, the call to `SuppressFinalize` is required if you have a virtual `Dispose` method and the containing type (`C` in this case). It does not matter whether a user-defined finalizer is present.

**Comment by JohanLarsson** [comment]
We keep it as default warning for now then.
