### ISSUE TITLE
C#8 handle using declarations

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/IDisposableAnalyzers#147]
```cs
public void M()
{
    using var stream = File.OpenRead(string.Empty); // disposed at end of scope.
    ...
}
```

**Comment by josh-degraw** [comment]
Is there any traction on this? This one seems like a pretty important use case for this analyzer to be able to handle.

**Comment by JohanLarsson** [comment]
Yes, absolutely. My problem is that half my department quit last year so it has been crazy at work.
And I did a horrible dumb putting master in a state that is not releaseable, couple of failing tests.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/IDisposableAnalyzers/3.0.0

Keep the issues coming!
