### ISSUE TITLE
IDISP011 – indicated in catch block with rethrow

### ISSUE THREAD

**Issue by JiriCepelkaFirstLineSoftware** [DotNetAnalyzers/IDisposableAnalyzers#184]
I got IDISP011 in case when instance is disposed in catch that rethrows the exception.

    public object ErrorExample()
    {
        var ms = new MemoryStream();
        try
        {
        }
        catch (Exception)
        {
            ms.Dispose();
            throw;
        }
    
        return ms; 
    }

**Comment by JohanLarsson** [comment]
Thanks for reporting!

**Comment by JohanLarsson** [comment]
For the code in the example there will be a warning since the return type is `object`
> IDISP005 Return type should indicate that the value should be disposed.

IDISP011 does not warn any more.

**Comment by JiriCepelkaFirstLineSoftware** [comment]
I am getting error also if ```MemoryStream``` is used instead of ```Object```.

`public MemoryStream ErrorExample()
{
		var ms = new MemoryStream();
		try
		{
		}
		catch (Exception)
		{
				ms.Dispose();
				throw;
		}

		return ms;
}`

**Comment by JohanLarsson** [comment]
Ah, ok that is probably fixed but not released. Closing a couple more issues then release of a new nuget.
Added a test with the code you provided and it is green. We reopen this issue or create a new issue if the bug is still around in the new version. Sorry about the inconvenience.

**Comment by jnyrup** [comment]
I'm seeing this (or related) with v3.3.2
depending on whether I use an `if` or null conditional.

```c#
public Stream Baz()
{
    Stream ms = null;
    try
    {
        ms = new MemoryStream();
    }
    catch
    {
        if (ms != null)
        {
            ms.Dispose();
        }

        throw;
    }

    return ms; // <-- IDISP011
}
```

```c#
public Stream Baz2()
{
    Stream ms = null;
    try
    {
        ms = new MemoryStream();
    }
    catch
    {
        ms?.Dispose();

        throw;
    }

    return ms; // <-- No warning
}
```
