### ISSUE TITLE
Do not warn about IDisposables in IHostedService

### ISSUE THREAD

**Issue by jeremyVignelles** [DotNetAnalyzers/IDisposableAnalyzers#186]
While during my unit tests, I was suprised that the IDisposable that I declare in my [SetUp] method and disposed in my [TearDown] were correctly understood by IDisposableAnalyzers.

I've seen that there might be an exception somewhere, because I saw those unit tests : https://github.com/DotNetAnalyzers/IDisposableAnalyzers/blob/759fc9bb091625c711675513729de83789e544d5/IDisposableAnalyzers.Test/IDISP002DisposeMemberTests/ValidCode.TestFixture.cs

Would it be possible to do the same for `IHostedService` ? I think it's a common pattern for background tasks in ASP.net core.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostedservice?view=dotnet-plat-ext-3.0
There are two methods : `StartAsync` and `StopAsync` which are called by the `IHost` implementation.
If I declare my Disposable in the StartAsync, and dispose them properly in the StopAsync, I think that it's a good usage of the IDisposable pattern.

**Comment by JohanLarsson** [comment]
Yes, it sounds reasonable, good suggestion. No idea when I will find time for it though, been crazy here lately.

**Comment by JohanLarsson** [comment]
Can you provide complete minimal sample code for a test?

**Comment by jeremyVignelles** [comment]
Here is an example: (written here, so it might not build)

```cs
using System.Threading;
using Microsoft.Extensions.Hosting;

public class Service: IHostedService
{
   private IDIsposable disposable; // Should not trigger IDISP002 nor IDISP006 : Usage is correct

   public Task StartAsync(CancellationToken token)
   {
      this.disposable = new Disposable(); // Should not trigger IDISP003 : not assigned from the constructor, and this method is made to be called only once. No need to dispose previous
   }

   public Task StopAsync(CancellationToken token)
   {
      this.disposable.Dispose();
   }
}
```

**Comment by JohanLarsson** [comment]
Should be easy, must find time.

**Comment by JohanLarsson** [comment]
Should the analyzer assume that `StartAsync` is only called once?

**Comment by jeremyVignelles** [comment]
Seems to me like a reasonable assumption. The host is only run once in the generated (by dotnet new) ASP.net core code, and I'm not sure that it supports being Started multiple times.

**Comment by jeremyVignelles** [comment]
Still triggers IDISP006 with this code:

```cs
    public class Test : IHostedService
    {
        private readonly SemaphoreSlim semaphore = new SemaphoreSlim(1);

        public Task StartAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            this.semaphore.Dispose();
            return Task.CompletedTask;
        }
    }
```
