### ISSUE TITLE
WinForms specific analyzers

### ISSUE THREAD

**Issue by josh-degraw** [DotNetAnalyzers/IDisposableAnalyzers#187]
There are some specific cases I've run into when analyzing `IDisposable` usages in a large legacy WinForms app that has led me to identify some cases where specific analysis rules would make sense. Some of these I'm not 100% sure what the _best_ course would be to address the specific issue, but I think it's at least worth a discussion.

### 1. `.Show()` vs `.ShowDialog()`
For example, when showing a form as a dialog, it ought to be properly disposed in the usual pattern, since it's effectively deterministic in its life cycle (i.e. it blocks the current method and no other forms can typically be accessed until it is closed, after which it's usually safe to dispose since it shouldn't need to be used again).

However, there are many cases where you create a `Form` and use `Show()` rather than `ShowDialog()` when the life cycle of the form is completely orthogonal and unknown to the calling code. In these cases it doesn't make sense to explicitly dispose since we have no way of knowing when the form will actually be closed.

So a proposal there could be for a specific analysis of disposal for `Form` and/or `Control` instances where the `Show()` method is called, rather than `ShowDialog()`.

### 2. Variables added to the `components` instance field
Another example I've run into is that in some cases there will be local variables initialized (i.e. a background worker) whose life cycle is unknown to the method that instantiates it, but that should not outlive the form, so it can be added to the designer-generated instance field `components` which disposes all `IDisposable` items it contains when the form is disposed.

In these cases it would make sense to check if the variable is added to either _just_ the `components` auto-generated field, or else some sort of instance field which is itself disposed eventually.

**Comment by JohanLarsson** [comment]
Sounds like good suggestions, I've never used winforms so gonna have to trust you :)
I don't know when I will find time for this analyzer, it is lagging behind badly.

**Comment by JohanLarsson** [comment]
Can you provide a complete minimal sample? I don't know winforms well so would be helpful with some code to use in a test.

**Comment by josh-degraw** [comment]
So as I said, I can't guarantee that my knowledge on this is 100% correct, but here are a few use cases.
1. Anything added to the automatically generated `components` field is disposed of.
```c#
class MyForm : Form
{
    private BackgroundWorker myWorker;
    MyForm()
    {
        myWorker = new BackgroundWorker(MyMethod);
        // Since this is added to components, it is automatically disposed of with the form.
        this.components.Add(myComponent); 
    }
}
```

2. Often you'll have an event handler that creates a form of some kind. As far as I understand it, if you have code like this within a control or form:
```c#
class MyForm : Form
{
    void MyEventHandler(object sender, EventArgs args)
    {
        var form = new OtherForm();
        form.Show();
    }
}
```
the lifetime of the `OtherForm` cannot be known by the calling method, it may outlive the calling method or class itself. So in this case it won't make sense to explicitly dispose of at all.

3. However, when using a form as a dialog, e.g.
```c#
class MyForm : Form
{
    void MyEventHandler(object sender, EventArgs args)
    {
        using(var form = new OtherForm())
        {
             if(form.ShowDialog() == DialogResult.OK)
             {
                 // handle success
             }
        }
    }
}
```
since the `ShowDialog()` method only returns after the form closes, it makes sense to ensure that the form is disposed of properly, so the existing analyzers fit just fine.

**Comment by JohanLarsson** [comment]
Nice, should be easy to add support. @jnm2 you know winforms well right?

**Comment by jnm2** [comment]
This looks right to me. I hadn't used the `components.Add` trick before, have been using an extension method `public static T Using<T>(this T lifetimeComponent, IDisposable componentToDispose) where T : Component` and doing this in the form constructor:

```
var someDisposable = this.Using(new SomeDisposable(...));
```

**Comment by JohanLarsson** [comment]
OK, making an exception for adding to components then, should be easy.

I'm not sure about 2, potentially problematic to leave it unhandled, tweaking the analyzer to not nag there should be easy..

**Comment by jnm2** [comment]
> I'm not sure about 2, potentially problematic to leave it unhandled

I don't think it's problematic. When Form.Close is eventually called, it disposes.

**Comment by jnm2** [comment]
New form template:

<details>
<summary>Form1.cs</summary>

```cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SomeNamespace
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
    }
}
```

</details>

<details>
<summary>Form1.Designer.cs</summary>

```cs
namespace SomeNamespace
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Text = "Form1";
        }

        #endregion
    }
}
```

</details>

**Comment by JohanLarsson** [comment]
Do you know if it is always named `components` or if it can pick up on code style and be named `_components`?

**Comment by jnm2** [comment]
I'm 99% sure that it doesn't pick up on code style.

**Comment by JohanLarsson** [comment]
@josh-degraw I don't use Winforms so I'm relying on you writing issues so we get things right. Nothing is too small, keep a steady stream of issues coming.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/IDisposableAnalyzers/3.2.0
