### ISSUE TITLE
IDISP001 does not handle "using declarations" introduced with C# 8.0

### ISSUE THREAD

**Issue by FreeApophis** [DotNetAnalyzers/IDisposableAnalyzers#189]
Before C# 8.0 we had to write a "using statement" like this (with or without the curly braces)
```CSharp
using (var reader = new StreamReader(templateStream))
{
    return reader.ReadToEnd();
}
```

[C# 8 introduces "using declarations"](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations) and Resharper already prefers the new syntax (which feels almost like C++ value semantics!)

```CSharp
using var reader = new StreamReader(templateStream)

// valid until the end of the scope
```

Sadly, we get an IDSP001, and for obvious reasons we do not want to deactivate that rule, but we prefer the new syntax.

**Comment by JohanLarsson** [comment]
Yes, this is absolutely terrible, must find time to fix it.

**Comment by JohanLarsson** [comment]
Releasing 3.0 now, keep the issues coming with things I'm dumbing for c# 8. Missing warnings etc.
