### ISSUE TITLE
IDISP004 listed but goes away when navigating to

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/IDisposableAnalyzers#198]
![Animation](https://user-images.githubusercontent.com/1640096/71877928-b13a5900-312a-11ea-8d03-9cc45d5d01ef.gif)

Perhaps due to symbol equality?

**Comment by Bouke** [comment]
I've seen this happen with other analyzers as well when I've set my Error List to show "Build + IntelliSense". Sometimes they can't agree on the errors so initially you're given the Build warnings, but when navigating to the error, IntelliSense decides it's no longer an issue. I don't know what to do about it, other than selecting "Build Only".

**Comment by AraHaan** [comment]
I think this is not a bug, another option is to select IntelliSense only too.

**Comment by JohanLarsson** [comment]
This is probably fixed, tried using the built in `SYmbolEqualityComparer` but switched back to own implementation.
