### ISSUE TITLE
Stackoverflow for generics

### ISSUE THREAD

**Issue by jnyrup** [DotNetAnalyzers/IDisposableAnalyzers#212]
IDisposableAnalyzers crashed my visual studio and I found the following code to be enough to reproduce the crash.

```c#
public class Foo
{
	public T Bar<T>(out T str)
	{
		return Bar(0, out str);
	}

	public T Bar<T>(int _, out T str)
	{
		str = default;
		return default;
	}
}
```

**Comment by JohanLarsson** [comment]
Sorry about this bug , thanks for reporting!

**Comment by JohanLarsson** [comment]
New version: https://www.nuget.org/packages/IDisposableAnalyzers/3.3.3

Again sorry about this bug.

**Comment by jnyrup** [comment]
No worries ❤️ 
I just tried to install this great analyzer to what it would find.
When it crashes I immediately suspected the class I dislike the most and it was indeed the culprit.
