### ISSUE TITLE
AD0001 Position is not within syntax tree with full span

### ISSUE THREAD

**Issue by drauch** [DotNetAnalyzers/IDisposableAnalyzers#223]
After updating to the newest version if IDisposableAnalyzers we get two errors in our solution when building our solution:

> Warning	AD0001	Analyzer 'IDisposableAnalyzers.CreationAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Position is not within syntax tree with full span [0..3101)	<ProjectName>	<AbsoluteProjectDirectoryPath>\CSC	1	Active

This is blocking our build. Do you know what the problem could be?

Best regards,
D.R.

**Comment by JohanLarsson** [comment]
My guess is I'm dumbing analysis when there is a partial class but not sure.
Is the analyzed code available on github?

**Comment by JohanLarsson** [comment]
A stack trace would be helpful here, sometimes the Visual Studio error can be expanded to show stack trace. Keep an eye open if you happen to see that.

**Comment by drauch** [comment]
We indeed have lots of partial classes. After ignoring IDISP025 globally, the error disappeared. Maybe that's a good hint for you?

Unfortunately, I cannot give you the corresponding source code, it's closed source.

If we encounter it again I will try to get the stack trace. Sorry for having so little information for you to work with.

Keep up the good work with this project!

Best regards,
D.R.

**Comment by JohanLarsson** [comment]
If you manage to narrow down a repro that I can use in a test the fix is likely simple. I'll do some reading and see if I can spot the mistake.

**Comment by JohanLarsson** [comment]
I tried to reproduce this issue but failed. `CreationAnalyzer` does not produce `IDISP025` are you sure that it was the ID you disabled?

**Comment by drauch** [comment]
I'm sure that I disabled this ID, yes. But maybe some other thing I also fixed prevented the error from reappearing...

Probably not worth it to invest lots of time now. The next time it occurs I will try to create a repro and will report back!

Thank you for your time!

Best regards,
D.R.

**Comment by fuocor** [comment]
I have the same issue as of this morning. using version 3.4.6

`
CSC : error AD0001: Analyzer 'IDisposableAnalyzers.LocalDeclarationAnalyzer' threw an exception of type 
 System.ArgumentOutOfRangeException' with message 'Position is not within syntax tree with full span [0..18285) (Parameter 'position') [...csproj]

CSC : error AD0001: Analyzer 'IDisposableAnalyzers.CreationAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Position is not within syntax tree with full span [0..18285) (Parameter 'position') [....csproj]
`
Attached is the detailed build log.
[msbuild.zip](https://github.com/DotNetAnalyzers/IDisposableAnalyzers/files/5636593/msbuild.zip)

**Comment by bash** [comment]
I have finally managed to find a somewhat small reproducible example for this error. I've opened a PR with a failing test case:
https://github.com/DotNetAnalyzers/IDisposableAnalyzers/pull/266

**Comment by JohanLarsson** [comment]
@bash awesome, thank you!

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/IDisposableAnalyzers/3.4.11
