### ISSUE TITLE
3.4.0 nupkg does not contain the analyzers

### ISSUE THREAD

**Issue by jnyrup** [DotNetAnalyzers/IDisposableAnalyzers#229]
The newly released 3.4.0 does not contain the analyzers dlls.

**Comment by JohanLarsson** [comment]
Ouch, thanks for reporting!

**Comment by JohanLarsson** [comment]
Not sure what happened there, been using `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` for a while. Updated Visual Studio, maybe a regression, will keep an eye open.

Republished https://www.nuget.org/packages/IDisposableAnalyzers/3.4.1 and unlisted 3.4.0
