### ISSUE TITLE
ArgumentNullException in DisposeMethodAnalyzer: Value cannot be null. (Parameter 'node')

### ISSUE THREAD

**Issue by sunsided** [DotNetAnalyzers/IDisposableAnalyzers#230]
I'm running into the following analyzer error when building a project:

```
  Analyzer 'IDisposableAnalyzers.DisposeMethodAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null. (Parameter 'node')'.
```

However when that happens, rebuilding the same project a couple of times appears to suppress it.

I'm not sure how to reproduce it consistently, but it seems to be related to #226 (`IDISP025` on `abstract void Dispose(...)` signatures). If I change the `abstract void Dispose(bool disposing)` in question to a `virtual void`, that seems to calm it.

**Comment by JohanLarsson** [comment]
Thanks for reporting, I'll have a look when I find time.
