### ISSUE TITLE
IDISP005 in ServiceDescriptor constructor while not in services.AddSingleton

### ISSUE THREAD

**Issue by jeremyVignelles** [DotNetAnalyzers/IDisposableAnalyzers#231]
Hi,

I am using Microsoft.Extensions.DependencyInjection and this code is triggering a IDISP005:

```cs
            services.Add(new ServiceDescriptor(typeof(ISecurityProvider), (sp) => new TestingSecurityProvider(), ServiceLifetime.Singleton));
```

`ISecurityProvider` is implementing `IDisposable`, but the ServiceDescriptor constructor takes a `Func<IServiceProvider, object>`  (can't guess the return type) but the service provider mechanism is known to dispose/disposeAsync the services when not needed anymore, so that's fine.

Not sure if this should be fixed, because that would require a special case for IServiceCollection/ServiceDescriptor, but you asked for issues 😄 

Also note that this code also shows the issue:
```cs
services.AddSingleton(typeof(ISecurityProvider), (sp) => new TestingSecurityProvider());
```

but not this one (because of the strong typing)

```cs
services.AddSingleton<ISecurityProvider>((sp) => new TestingSecurityProvider());
```

**Comment by JohanLarsson** [comment]
> Not sure if this should be fixed, because that would require a special case for IServiceCollection/ServiceDescriptor, but you asked for issues

We should aim to special case common APIs, keep the issues coming. Sorry about the delay.

**Comment by jeremyVignelles** [comment]
I have another case (regression) in the version I use which is related to this one. I didn't have time to report it yet. It's something like:

```cs
services.AddSignleton<ISomeInterface>(sp => new SomeImplementation());
```

If `ISomeInterface` is not disposable but `SomeImplementation` is, it says that the return type should indicate it's Disposable. The ServiceProvider doesn't care and tests if the implementation is Disposable/AsyncDisposable

**Comment by JohanLarsson** [comment]
I'll see if I can repro and include fix for it.

**Comment by JohanLarsson** [comment]
The issues is likely that we need to tell the analyzer that `ServiceCollection` owns the things passed in. Easy fixes but we have to do it issue by issue. There are heuristics that the analyzer uses to guess about APIs from binary references, they are not always right.
