### ISSUE TITLE
Legacy protected dispose pattern

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [DotNetAnalyzers/IDisposableAnalyzers#232]
Does anyone have any information about why the protected dispose pattern is marked as "LEGACY" in this analyzer? It looks to me like using `protected virtual Dispose(bool disposing)` aligns more closely with the suggested Dispose pattern that can be found on MSDN, so I'm not sure why it's labeled as "legacy".

Thanks :)

**Comment by jnm2** [comment]
The only reason to have a `protected virtual Dispose(bool disposing)` method is to accomodate derived classes that go against the current guidance (finally updated in the docs!) of using SafeHandle and avoiding declaring finalizers. https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/unmanaged:

> **⚠ Warning**
>
> However, because object finalization can be a complex and an error-prone operation, we recommend that you use a safe handle instead of providing your own finalizer.

The framework team [recently confirmed](https://github.com/dotnet/docs/pull/18266#discussion_r423081403) during recent updates to the docs that the pattern is still for unsealed classes to use `protected virtual Dispose(bool disposing)`. This is not what some of us were expecting and I'm not sure I fully understand why this is useful, given that finalizers are avoidable and docs say to stay away from them.

**Comment by jnm2** [comment]
Because I can't build an adequate case for why `protected virtual Dispose(bool disposing)` is better than just having `public virtual void Dispose()`, I'm asking for clarification here: https://github.com/dotnet/docs/pull/18266#discussion_r459675736

**Comment by sharwell** [comment]
@jnm2 I was in the meeting. The conclusion is the dispose guidelines for public APIs (libraries, etc.) are the ones documented on that page. If you don't want to follow the framework design guidelines, whether for simplicity or because you don't intend to support downstream clients with finalizers, then you can use a different design policy which may or may not comply with that document.

**Comment by jnm2** [comment]
> whether for simplicity or because you don't intend to support downstream clients with finalizers

This is the part that I'm hoping to gain understanding on. Does providing a virtual `Dispose()` and no `Dispose(bool)` mean that downstream clients with finalizers aren't supported? And why?

> Even if the base class doesn't have `Dispose(bool)`, can't the derived class always work around this via composition by encapsulating the finalizer in a separate class outside the inheritance hierarchy? And for sealed derived classes, can't they just declare a finalizer and override `Dispose()` to suppress finalization and call `base.Dispose()`?

**Comment by sharwell** [comment]
Yes, it means that a derived type cannot safely add a finalizer. Though I would argue the use of the full dispose pattern doesn't do a great job of ensuring the opposite. 😄

**Comment by jnm2** [comment]
What is the reason that a derived class cannot safely add a finalizer?

**Comment by sharwell** [comment]
I suppose it could add a finalizer, but it couldn't call `base.Dispose()` from the finalizer.

**Comment by jnm2** [comment]
Why would it want to call `base.Dispose()` from the finalizer when the base class has no unmanaged resources?

**Comment by Bosch-Eli-Black** [comment]
@sharwell, I'm curious about this as well :)

**Comment by sharwell** [comment]
Not sure why we'd need to be pedantic about options for adding a user-defined finalizer. Having the pattern support it doesn't make it any less of a bad idea. 😄

**Comment by jnm2** [comment]
Not sure I fully get what you meant, but to sum up my understanding so far:

- The official pattern recommends the use of finalizers without giving sufficient reasoning to support it versus the same pattern minus the use of finalizers.
- The best we can tell is that not having a finalizer will never paint a class or its derived classes into a corner. The derived class can *always* encapsulate the unmanaged resource into a new class outside the inheritance hierarchy, whether the new class is based on SafeHandle or has a user-declared finalizer.

So to answer the question at the top, the analyzer declares finalizers to be legacy because its opinion is that the official pattern is recommending something legacy that you should not do. Should it stop having its own opinion? What are the pros and cons?

**Comment by JohanLarsson** [comment]
@Bosch-Eli-Black we can close this right?
Thanks everyone for a great thread!

**Comment by Bosch-Eli-Black** [comment]
@JohanLarsson Actually, I think this is still relevant 😆

The original issue hasn't really been resolved: The disposable pattern that Microsoft recommends is labeled as the "LEGACY" pattern in this analyzer, while the analyzer's recommended disposal pattern isn't the way that Microsoft recommends.

**Comment by JohanLarsson** [comment]
Ok, how should we improve the situation? I did not put much thought into `LEGACY`

**Comment by sharwell** [comment]
@Bosch-Eli-Black the analyzer encourages the use of a newer and much simpler pattern over the pattern originally developed, leveraging best practices information learned in the meantime. I would recommend changing 'legacy' to 'full', but without question would continue to discourage its use. The only cases where the 'full' pattern makes sense are:

1. A public library which already has an established public API that consistently uses the full pattern (this would include developing new code in the BCL)
2. Implementing a type which derives from a base class that use the full pattern, e.g. `Form`

**Comment by JohanLarsson** [comment]
For 2 we detect this and generate the override
![Animation](https://user-images.githubusercontent.com/1640096/99565865-72bd2e00-29cc-11eb-9f7e-642b0f6aff06.gif)
.

**Comment by jnm2** [comment]
Following up, this is the reason that the official docs still recommend the old pattern:

> The biggest reason is consistency... so that there's not one pattern for types that were declared in 2020 and another for older types.
>
> We had a big discussion about this last winter and that was our basic conclusion: we've had a pattern for 15+ years, and it's too disruptive to change it (and the pattern isn't very expensive).

https://github.com/dotnet/runtime/discussions/41493#discussioncomment-58355

I think svick's comment under that answer is excellent, but now we know why the docs still recommend what we consider legacy.

**Comment by Bosch-Eli-Black** [comment]
Thanks for all of the great information! 🙂

Personally, I'm fine with the fact that the primary quickfix in IDisposableAnalyzers implements a disposable pattern that doesn't include a finalizer. I guess I was mostly just confused by the fact that the quickfix that implements the "full" disposable pattern is labeled as "LEGACY".

For me, I think that changing the wording from "LEGACY" to "full" or something like "Implement IDisposable, using finalizers" would be enough to clarify things 🙂

**Comment by JohanLarsson** [comment]
I think I prefer LEGACY as it indicates that it is not the preferred pattern by this opinionated analyzer.

My thinking is that full could be interpreted as this is what you want if you want to do it properly.

**Comment by Bosch-Eli-Black** [comment]
@JohanLarsson Okay, works for me. Thanks to everyone for providing clarification on this topic :)
