### ISSUE TITLE
IDISP001: Ignore when Dispose is delegated by ASP.NET

### ISSUE THREAD

**Issue by m0ddixx** [DotNetAnalyzers/IDisposableAnalyzers#234]
In Asp.Net Core the Method RegisterForDispose(object? obj) and RegisterForDisposeAsync(object? obj) on HttpResponse are delegating the Disposal after the Response has finished. Which is helpful for some models, whose are passed until the ViewEngine renders the DOM. I'd like to supress the warnings when scenarios like these happen.
Thank you

**Comment by JohanLarsson** [comment]
Thanks for reporting. Do you happen to have a minimal sample we can use in tests? I don't write any asp so chances are I'd dumb using the API.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/IDisposableAnalyzers/3.4.5
