### ISSUE TITLE
Debug statement in install script?

### ISSUE THREAD

**Issue by Bouke** [DotNetAnalyzers/IDisposableAnalyzers#238]
https://github.com/DotNetAnalyzers/IDisposableAnalyzers/blob/6b7b7206f67b7fe3d78b76a9ca5c38a74998b91f/IDisposableAnalyzers/tools/install.ps1#L20

I believe this prints "C#" during installation of the page. Is this a debug statement that was left by accident?

**Comment by JohanLarsson** [comment]
I copied it from the internet :)
