### ISSUE TITLE
Release notes for 3.4.3?

### ISSUE THREAD

**Issue by Bouke** [DotNetAnalyzers/IDisposableAnalyzers#243]
Thanks again for this great package. I see version 3.4.3 was released a few days ago, but I couldn't find the release notes. Is it possible to provide them?

**Comment by JohanLarsson** [comment]
I'm so terrible, sorry about this. I'll try to dig some out of history.

**Comment by Bouke** [comment]
For me ideal the release notes warn me of breaking changes, and for analyzers whether new analyzers enabled/disabled by default and whether their severity had maybe changed. The notes you've added are just fine for me, thank you!
