### ISSUE TITLE
IDISP0023 when two not chained constructors

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/IDisposableAnalyzers#273]
```cs
public sealed class C : IDisposable
{
    private readonly Disposable disposable;

    public C(int x, int y)
        : this(x + y)
    {
    }

    public C(int x)
    {
        this.disposable = new Disposable();
    }

    public C(string x)
    {
        this.disposable = new Disposable();
    }

    public void Dispose()
    {
        this.disposable.Dispose();
    }
}
```

Not sure if ^ is a repro.

**Comment by AraHaan** [comment]
It also warns saying dispose injected when you use a private static variable that is disposable, do not dispose of it at the Dispose(bool) method of the class, and when someone calls a ctor that then makes an new instance of said Disposable and does ``this.disposable?.Dispose();`` before setting ``this.disposable = new Disposable(container);``

However here is example code (uses NotifyIcon from System.Windows.Forms):

In this code one should *really* use the ctor that passes a container, the private static would then be added to that container and then disposed of when said container is disposed of.

Oddly enough if you remove the notifyIcon?.Dispose() you should be able to reproduce yet another issue too (I never really wanted the dispose in the ctor but 😨).
```cs
    public class MessageManager : Control
    {
        private static NotifyIcon notifyIcon;

        public MessageManager()
        {
            notifyIcon?.Dispose();
            notifyIcon = new NotifyIcon();
        }

        public MessageManager(IContainer container)
        {
            notifyIcon?.Dispose();
            notifyIcon = new NotifyIcon(container);
        }

        // hopefully notifyIcon is disposed of by the container provided when constructing this class when it is disposed.
        protected override void Dispose(bool disposing)
            => base.Dispose(disposing);
    }
```

**Comment by JohanLarsson** [comment]
The nag about disposing the static is by design even if the wording in the warning can be improved.

```cs
class C
{
    static IDisposable;
    
    C()
    {
        disposable?.Dispose(); // We potentially dispose what is created by another instance of the class 
        disposable = ...
    }
}
```

This is not a great design and if it is intentional I think a #pragma explaining why is a good idea.
