### ISSUE TITLE
Release notes for 4.0.0?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [DotNetAnalyzers/IDisposableAnalyzers#342]
It looks like the release notes for release 4.0.0 are missing from https://github.com/DotNetAnalyzers/IDisposableAnalyzers/blob/master/RELEASE_NOTES.md 🙂

**Comment by JohanLarsson** [comment]
Ew, sorry about that, thanks for the reminder.

**Comment by Bosch-Eli-Black** [comment]
No worries! 🙂

**Comment by Bouke** [comment]
What does "BREAKING: For VS2022+ now." mean? Does the analyzer only work with Visual Studio 2022 (and greater)? What about other versions, tooling? e.g. MSBuild and Rider?

**Comment by JohanLarsson** [comment]
It uses Microsoft.CodeAnalysis.CSharp 4.0.1 so Visual Studio 2022+.
I don't know what Rider uses but assume they are fast at updating. Easiest is to try I think.
