### ISSUE TITLE
IDISP023: what does "AV" mean?

### ISSUE THREAD

**Issue by Bouke** [DotNetAnalyzers/IDisposableAnalyzers#427]
https://github.com/DotNetAnalyzers/IDisposableAnalyzers/blob/bfe166ffb816373341a9495a2ec1848832dfffb2/documentation/IDISP023.md?plain=1#L19

>  could AV and crash the process

What does "could AV" mean in this context? AccessViolationException?

**Comment by JohanLarsson** [comment]
I don't know, may have copied that text from somewhere.
Changed AV to access violation.

**Comment by Bosch-Eli-Black** [comment]
Thanks! 🙂
