### ISSUE TITLE
IDISP004 doesn't warn when `Task<>.FromResult(disposable)` is returned by a method, but does when `new ValueTask<>(disposable)` is returned.)

### ISSUE THREAD

**Issue by JeremyMorton** [DotNetAnalyzers/IDisposableAnalyzers#470]
Can returning a disposable object as the result of a `ValueTask<>` not raise this. returning a disposable object as the result of a `Task<>` already doesn't raise it.

**Comment by JohanLarsson** [comment]
Ah, I rarely use `ValueTask` so support is still limited, thanks for the issue!
