### ISSUE TITLE
IDISP003,IDISP007,IDISP008... many bugs

### ISSUE THREAD

**Issue by fahadabdulaziz** [DotNetAnalyzers/IDisposableAnalyzers#51]
Hi, 

Thank you for fast updating the analyzers, really great job 👍 

I have these bugs to report (or maybe I'm doing something wrong), I took screenshots:
![idisp1](https://user-images.githubusercontent.com/5483584/36736802-8341dade-1bea-11e8-9827-e7ac1f9298a0.png)
================
![idisp2](https://user-images.githubusercontent.com/5483584/36736804-8371cf32-1bea-11e8-9ce6-d2e7fcd8743f.png)
================
![idisp3](https://user-images.githubusercontent.com/5483584/36736805-83a2940a-1bea-11e8-8336-d95258c1397a.png)

Also previously reported bugs not all fixed,  attached sample code contains these issues:
[ConsoleApp4.zip](https://github.com/DotNetAnalyzers/IDisposableAnalyzers/files/1763557/ConsoleApp4.zip)

I'll try to reproduce these error in one sample project to be easy to work on.

Thank you

**Comment by JohanLarsson** [comment]
Best is if you write many issues with minimal sample code reproducing the bug, then we can use the repro cod in tests and close the issues one by one.

**Comment by JohanLarsson** [comment]
About the HttpClient: It is specialcased checking that it is a static field or property.
```cs
private static HttpClient Client =new HttpClient { ... };
```
Is the way to mute it, updated the [docs](https://github.com/DotNetAnalyzers/IDisposableAnalyzers/blob/master/documentation/IDISP014.md#motivation)

**Comment by JohanLarsson** [comment]
The IDISP008 for the field looks correct as you have a public setter combined with assigning it lazily in the getter, we have no idea if we should dispose it.

**Comment by JohanLarsson** [comment]
I'm mixed about supporting:

```cs
namespace RoslynSandbox
{
    using System.IO;

    public class Foo
    {
        private readonly string fileName;
        private Stream stream;

        public Stream Stream
        {
            get
            {
                if (this.stream == null && this.fileName != null)
                {
                    this.stream = File.OpenRead(this.fileName);
                }

                return this.stream;
            }
        }
    }
}
```

As it is not thread safe.

**Comment by JohanLarsson** [comment]
I'm closing this as the analyzer does the right thing in most places in the screenie. In the future it is preferable with one issue per bug with a minimal repro.
