### ISSUE TITLE
Does IDisposableAnalyzers 2.0.2 support .Net 4.7.1 ?

### ISSUE THREAD

**Issue by kuzyaka** [DotNetAnalyzers/IDisposableAnalyzers#78]
Does IDisposableAnalyzers 2.0.2 support .Net 4.7.1 ?
I cannot update existing 1.0.0. reference in .net 4.7.1 project to 2.0.2 because of target error.

**Comment by JohanLarsson** [comment]
What Visual Studio version are you using? The > 2 version of the package is for VS2017.

**Comment by kuzyaka** [comment]
Same error in both VS 2017 15.5.7 and Rider 2018.1

**Comment by JohanLarsson** [comment]
Ok, not sure what I dumbed, I'll try to repro. Did you try close VS and git clean after updating?

**Comment by kuzyaka** [comment]
I got this error during update process and IDisposableAnalyzers nuget package version remains 1.0.0
In other words I cannot do it after updating because there is no any updating

**Comment by JohanLarsson** [comment]
This might be a tricky one, I'll dig around.
I updated a couple of projects successfully using paket.

**Comment by kuzyaka** [comment]
I found workaround - Update packages.config in text editor and then "nuget.exe restore" in command line.
I'm wondering it does not work in UI wizards.

**Comment by JohanLarsson** [comment]
Possible nuget.exe bug, we leave the issue open for digging around some.
