### ISSUE TITLE
IDISP004 vs ApplicationInsights LoggerFactory

### ISSUE THREAD

**Issue by nulltoken** [DotNetAnalyzers/IDisposableAnalyzers#90]
As described **[here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Logging)**, I use ApplicationInsights as a sink for traces

```csharp
public void Configure(
    IApplicationBuilder app,
    IHostingEnvironment env,
    ILoggerFactory loggerFactory)
{
    /*....*/
    loggerFactory
         .AddApplicationInsights(app.ApplicationServices, LogLevel.Warning); // IDISP004

}
```

Unfortunately, the `.AddApplicationInsights()` method is a "Fluent" method that returns a `ILoggerFactory` which makes `IDISP004` somehow unhappy.

My understanding is that the `ILoggerFactory` lifecycle is handled by the underlying framework.

**Comment by JohanLarsson** [comment]
Fluent is always going to be tricky. I think we need to handle them case by case fir binary references.
Question is if our default assumption is bad.

**Comment by JohanLarsson** [comment]
In my weirdest moments I have thought about decompiling and walking the decompilation :D
I know it is a terrible idea.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/IDisposableAnalyzers/2.0.3.2

Sorry about the delay, keep the issues coming!
