### ISSUE TITLE
IDISP004 vs IApplicationLifetime

### ISSUE THREAD

**Issue by nulltoken** [DotNetAnalyzers/IDisposableAnalyzers#91]
In a web app, triggering thingies on startup and/or shutdown may actually be useful for monitoring purposes.

Unfortunately, `IDISP004` sulks in displeasure about the undisposed `CancellationToken`s

```csharp
public void Configure(
    IApplicationBuilder app,
    IHostingEnvironment env,
    ILoggerFactory loggerFactory,
    IApplicationLifetime lifetime)
{

    /* ... */

    lifetime.ApplicationStarted.Register(() =>
    {
        var @event = new EventTelemetry("Application.Started");
        telemetryClient.TrackEvent(@event);

        if (env.IsDevelopment())
        {
            logger.LogWarning("Application is running in 'Development' mode");
        }
    }); // IDISP004 

    lifetime.ApplicationStopping.Register(() =>
    {
        var @event = new EventTelemetry("Application.Stopping");
        telemetryClient.TrackEvent(@event);

        telemetryClient.Flush();

        // Allow some time for flushing before shutdown.
        Thread.Sleep(1000);
    }); // IDISP004 

    /* ... */

}
```

code above shamelessly inspired from **[live.asp.net](https://github.com/aspnet/live.asp.net/blob/783fb5933d91c498b04423efdab9665b8c27d8a9/src/live.asp.net/Services/AppStart.cs)** (Apache License, Version 2.0)

/cc @DamianEdwards

**Comment by JohanLarsson** [comment]
Thanks for the issue, I'll have a look at it, I don't know these APIs as I am a desktoposaurus.

**Comment by JohanLarsson** [comment]
What nuget package do I need to add to make this compile?

**Comment by JohanLarsson** [comment]
I think the warning is correct here. As I read the API the call to `Register` returns a `CancellationTokenRegistration` that can be used to unregister.

One way to mute the warning and make it clear that it is intentional is to discard the returnvalue:

```cs
_ = lifetime.ApplicationStarted.Register(...);
```

I'm leaving this open for a while in case I did not understand the API.

**Comment by JohanLarsson** [comment]
Is this still an issue?

**Comment by nulltoken** [comment]
@JohanLarsson Sorry for the delay answering and thanks for the kind reminder. As a matter of fact, I completely overlooked your previous comment. :disappointed: 

The workaround is great and makes it very explicit. Thanks a lot for pointing it a me.  :heart: 

No longer an issue, then.

**Comment by JohanLarsson** [comment]
Chances are I dumbed it with #117 and brought the issue back. Might need tweaking, keep the issues coming!

**Comment by nulltoken** [comment]
> Chances are I dumbed it with #117 and brought the issue back.

![image](https://user-images.githubusercontent.com/92363/47497710-48373000-d85b-11e8-9d0d-09e921fd1847.png)

>keep the issues coming!

Sir! I will, Sir!
